:toc:

= Learning Typescript

== Links

* https://www.typescriptlang.org/docs/handbook
* https://www.typescriptlang.org/play/ - Playground with tsconfig wizard

== Caveats for Java / Kotlin programmers

Values can not only be of one type but also of a set of types. I.e. something returned as "string | number" is either of those types.

Types are "structural types", not "nominal types", i.e. if an object has the properties "x" and "y", you can pass it to a function that expects a parameter of the "Point" interface type. If it also has a property "name", it additionally satisfies all interfaces that just require such an attribute.

Types also are not "reified", i.e. they lose all information about their type at runtime.


== Modules

Since ES2015, the ECMA Module System (ESM) with "import"/"export" is preferred over the legacy CommonJS system
with "module.exports"/"require".

Module files can explicitly be name "*.cts" or "*.mts" to have them use one style despite `package.json` specifying the other.
Beware, though, that the extra suffixes need to be registered in `tsconfig.json` as well as `jest.config`.

Links:

* https://betterstack.com/community/guides/scaling-nodejs/commonjs-vs-esm/

== Tools

tsc::
This is the Typescript to Javascript compiler. It can be configured using `tsconfig.json`.

babel::
A Javascript transpiler that can be used to transform any Javascript version to any older one. In this case it is used instead of "tsc" to transform Typescript into the version of Javascript, that NodeJS can work with. It does only the compilation and cannot do static type checking. For that we need either "tsc" or just our IDE.

eslint::
A static linter, i.e. syntax checker. Is configured wit the "StandardJS" rule set so that we do not need the prettier tool. Uses `eslintrc.json`.
We do have an additional `.editorconfig` file to control e.g. tab size.

npm::
NodeJs Packet Manager. Like "Gradle". Can be used to install or manage dependencies and run everything that is defined in the `package.json` section `script` section.

npx::
NodeJs Packet Executer. Runs a CLI package immediately. Prefers the version in `node_modules/` but can as well download one into a temporary cache.

volta::
NodeJs environment manager. Provides access to the npm/node versions that are defined as "engine" in package.json.

 npx jest                 # runs the Jest test suite
 npx typescript@5.9 tsc   # Runs `tsc` from the specified package

=== npm

Problems with IPv6?

    NODE_OPTIONS=--dns-result-order=ipv4first npm --loglevel=verbose ci

=== volta

Use like

    volta run npm ci
